### ISSUE TITLE
add_cp_cols drops observations when station code does not match any in station_source 

### ISSUE THREAD

**Issue by bristol-emily** [BLE-LTER/bleutils#4]
Can we add an option that retains unrecognized stations in the output dataframe? Alternatively, we could at least throw a warning that there wasn't a match in station_source for all station codes in the input dataframe.

**Comment by atn38** [comment]
Hi Emily, I'm aware that this happens but hasn't had incentive to change it
so far. thanks for reporting this :) The warning seems appropriate.
Retaining the rows are a little bit more undesirable for me, but we can do
that as an option as well.

**Comment by atn38** [comment]
Hey Emily, check out the new commit and see if it solves your issue?

**Comment by bristol-emily** [comment]
The warning works nicely, thanks for this! 

One issue I noticed is that add_cp_cols reorders my dataframe. For the CDOM data, I like to have the wavelengths in numerical order so I had to write a line of code to reorder it. Not a big deal, but I couldn't figure out what is causing the reordering.
